//
// Generated file, do not edit! Created by nedtool 5.4 from veins/modules/application/platooning/messages/MoveToPosition.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __MOVETOPOSITION_M_H
#define __MOVETOPOSITION_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>veins/modules/application/platooning/messages/MoveToPosition.msg:29</tt> by nedtool.
 * <pre>
 * // Request to move the correct position.
 * // Is sent from the leader of the Platoon to an accepted joiner.
 * // Needs a successful JoinResponse to be sent be before.
 * // Contains information about the Platoon and the position to join.
 * packet MoveToPosition extends ManeuverMessage
 * {
 *     double platoonSpeed;
 *     int platoonLane;
 *     int newPlatoonFormation[];
 * }
 * </pre>
 */
class MoveToPosition : public ::ManeuverMessage
{
  protected:
    double platoonSpeed;
    int platoonLane;
    int *newPlatoonFormation; // array ptr
    unsigned int newPlatoonFormation_arraysize;

  private:
    void copy(const MoveToPosition& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MoveToPosition&);

  public:
    MoveToPosition(const char *name=nullptr, short kind=0);
    MoveToPosition(const MoveToPosition& other);
    virtual ~MoveToPosition();
    MoveToPosition& operator=(const MoveToPosition& other);
    virtual MoveToPosition *dup() const override {return new MoveToPosition(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getPlatoonSpeed() const;
    virtual void setPlatoonSpeed(double platoonSpeed);
    virtual int getPlatoonLane() const;
    virtual void setPlatoonLane(int platoonLane);
    virtual void setNewPlatoonFormationArraySize(unsigned int size);
    virtual unsigned int getNewPlatoonFormationArraySize() const;
    virtual int getNewPlatoonFormation(unsigned int k) const;
    virtual void setNewPlatoonFormation(unsigned int k, int newPlatoonFormation);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MoveToPosition& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MoveToPosition& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MOVETOPOSITION_M_H

